domain_path: /home/kerngt/work/zynqmp/xli_v2024_1_wk/kr260_amp_uart_release/software_wk/kr260_amp_uart.vitis/pf_amp_uart_r5_0/export/pf_amp_uart_r5_0/sw/freertos_psu_cortexr5_0
app_src_dir: /tools/Xilinx/Vitis/2024.1/data/embeddedsw/lib/sw_apps/freertos_hello_world
template: freertos_hello_world
