domain_path: /home/kerngt/work/zynqmp/xli_v2024_1_wk/kr260_amp_uart_release/software_wk/ZynqMP-UART-AMP-KR260-Ubuntu/r5_firmware.vitis_unified_ide/pf_amp_uart_r5_1/zynqmp_fsbl/zynqmp_fsbl_bsp
app_src_dir: /tools/Xilinx/Vitis/2024.1/data/embeddedsw/lib/sw_apps/zynqmp_fsbl
template: zynqmp_fsbl
